### ISSUE TITLE
В визуализаторе непонятно какой игрок где

### ISSUE THREAD

**Issue by dbf256** [MailRuChamps/raic-2020#1]
Можно или расположить подписи со статистикой по соответствующим углам или хотя бы разместить их в виде 2 строки по 2 столбца (как квадраты игроков).

**Comment by Tairesh** [comment]
Хорошо бы в таблице вверху ники игроков выводить тем же цветом, что и их юниты

**Comment by Karloid** [comment]
порядок сейчас такой
```
4 2
1 3
```
но цвета нужны да, и мб покрупнее скоры

**Comment by dbf256** [comment]
Спасибо за добавление цветов к тексту, единственное - не очень удачный жёлтый т.к. на нем плохо видны белые значки из-за того, что он очень яркий и при некоторых проблемах с цветовосприятием он смешивается с зеленым. 
Нельзя ли сделать его каким-то более темным, например, чёрным, темно-серым или, например, ярко-оранжевым?

**Comment by kuviman** [comment]
Fixed
