### ISSUE TITLE
Ослабьте пожалуйста ограничение в 3 посылки в 20 минут для тестовых игр

### ISSUE THREAD

**Issue by udalov** [MailRuChamps/raic-2020#102]
Пытаюсь пофиксить ошибку верификации, не воспроизводящуюся локально, и для того, чтобы её локализовать, делаю тестовые посылки. Но ограничение в 3 посылки в 20 минут очень мешает. Может, его можно ослабить хотя бы для тестовых посылок?

**Comment by oPOCCOMAXAo** [comment]
Предлагаю ввести донат на увеличения количества тестовых игр)
Вполне оправдано - деньги пойдут на оплату хостинга

**Comment by kuviman** [comment]
Увеличили
