### ISSUE TITLE
Сайт не показывает текст ошибки компиляции

### ISSUE THREAD

**Issue by luckman** [MailRuChamps/raic-2020#111]
Раньше при падении программы по компиляции можно было кликнуть на надпись
![image](https://user-images.githubusercontent.com/2941360/102097964-a22e5180-3e37-11eb-8f63-0372a6d2191a.png)
и отображалось, где конкретно упала программа

На новых попытках (как минимум, начиная с воскресенья) никаких сообщений не выводится. Запрос из браузера, ведущий на POST https://russianaicup.ru/data/errorLog возвращает пустой респонс

Пример: попытка 17536

Невозможно понять в чём ошибка программы без каких-либо сообщений. Локально собирается и при помощи Oracle Java 15, и Open JDK 15

**Comment by kuviman** [comment]
Для новых посылок должно показываться. В целом есть два случая - превышение лимита времени и памяти при компиляции

**Comment by luckman** [comment]
Попытка №18775 (отправлена в 19:45 мск)
Не показывает

Пока попробую Graal ещё, но хотелось бы чтобы и обычная Java отрабатывала
