### ISSUE TITLE
Стартовать локалраннер центрированным на центр карты и с масштабом так чтобы все влезало

### ISSUE THREAD

**Issue by uppi** [MailRuChamps/raic-2020#12]
Сабж. Сейчас каждый просмотр требует ручной настройки в одно и то же положение

**Comment by mrlewap** [comment]
На макосе каждый раз так запукается:
![image](https://user-images.githubusercontent.com/1180274/100547141-53a58280-328f-11eb-99b7-b8bf153336d1.png)

**Comment by uppi** [comment]
И в хроме тоже, и на маке и на винде

**Comment by kuviman** [comment]
Fixed
