### ISSUE TITLE
bug building builder unit and ranged unit simultaneously whithout enough resources

### ISSUE THREAD

**Issue by wala8963** [MailRuChamps/raic-2020#120]
I play locally against an older version of my AI

**ROUND 188 :**
![bug1](https://user-images.githubusercontent.com/47273335/102779286-406c6b00-4394-11eb-9fac-378222405821.PNG)
**ROUND 189 :**
![bug2](https://user-images.githubusercontent.com/47273335/102779388-6c87ec00-4394-11eb-9604-95d5c93679b6.PNG)

The problem is with the player 2 : between the 2 rounds i give the actions to build a builder unit and a ranged unit. Only the builder unit is build (but **my resources go from 32 to 9 and a builder unit only costs 10**)
Until this round both my AI did exactly the same things (same resource number...)

**Comment by nnovich-OK** [comment]
Builder costs (10 + number of already existing builders) which totals at 34 in your case. So 32 initial resource + income from round 188 - 34 spent = 9 left. I don't see any issues.

**Comment by wala8963** [comment]
I didn't know about the number of already existing builders. thanks.
