### ISSUE TITLE
Поменять тип моделей с структур на классы в языковом пакете C#

### ISSUE THREAD

**Issue by vahpetr** [MailRuChamps/raic-2020#13]
На всех(вроде как) прошлых соревнованиях модели в языковом пакете C# были классы, а сейчас это структуры. 
Со структурами работать сложнее.
Конвертировать при получении в классы работа неблагодарная и затратная.
Свою реализацию моделей со стратегией передать нельзя, контейнер свой собрать нельзя.
Прошу вернуть тип со структур на классы в моделях.

**Comment by kuviman** [comment]
Генерация клиентов такая же, как в прошлом году. Свою реализацию моделей делать можно.

**Comment by mortido** [comment]
Простое решение - своя модель и в нее перегнать их модели. Можно пойти сложнее и менять их модели (да, они не будут подменяться на сервере).
К слову это вкусовщина и один класс с типом, лично мне, больше зашел тут. Теже действия сделаны через эпопею классов и уже не так весело, когда можно сделать 1 класс и методы move/attack/auto_attack/repair которые выставляют нужные поля. В общем большой простор для своих переписываний и траты времени =)
