### ISSUE TITLE
Исчезают элементы управления в плеере

### ISSUE THREAD

**Issue by dbf256** [MailRuChamps/raic-2020#14]
https://clip2net.com/s/4a160ml
В ходе прокручивания строки прогресса игры пропадают элементы управления.
Стабильно воспроизвести не удается, так что только если что-то есть в логах, игра https://russianaicup.ru/game/view/1360 проиграно со страницы https://russianaicup.ru/profile/Recar, Win 7, Firefox.

**Comment by kuviman** [comment]
Падение кажется только при включенной графике, в схематичном виде не воспроизводится (кнопка V)

**Comment by kuviman** [comment]
Вероятно пофикшено
