### ISSUE TITLE
Юниты цвета морской волны плохо видны на сером фоне

### ISSUE THREAD

**Issue by uppi** [MailRuChamps/raic-2020#18]
![image](https://user-images.githubusercontent.com/1144071/100548312-c822f600-327c-11eb-9a33-b924966cddb4.png)

Было бы клево потвикать цвета в сторону увеличения контраста

**Comment by Altaire13** [comment]
Предлагаю для этого и фон затемнить.
В текстурированном режиме обведенные юниты на темном фоне видны просто замечательно. Не хотелось бы, чтобы схематичный режим был бы хуже в плане информативности.

**Comment by kuviman** [comment]
Цвета поменяли
