### ISSUE TITLE
Вынести неизменную информацию из PlayerView в ServerMessage Init

### ISSUE THREAD

**Issue by vahpetr** [MailRuChamps/raic-2020#19]
Предлагаю добавить команду ServerMessage Init который будет при старте инициализировать стратегию с параметрами настройки мира:
MyId, MapSize, FogOfWar, EntityProperties, MaxTickCount, MaxPathfindNodes
Убрать эти поля из объекта PlayerView и не передавать их каждый раз.
Это позволит уменьшить объём передаваемой информации и упростить код стратегии.

**Comment by kuviman** [comment]
Количество данных здесь достаточно маленькое, по сравнению с количеством изменяемой информации (сущности), так что объем увеличится не сильно.

Это изменение приведет к изменению протокола взаимодействия, так что, думаю, нежелательно

**Comment by kuviman** [comment]
в общем, не в этот раз
