### ISSUE TITLE
Баг Сафари

### ISSUE THREAD

**Issue by SannikovDmitry** [MailRuChamps/raic-2020#2]
Визуализатор стакинг на тиках сайт
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/18384737/100537775-575be980-323c-11eb-8704-a434977fb92e.png">

**Comment by romka-u** [comment]
Тоже пару раз натыкался.

**Comment by kuviman** [comment]
Кажется то же самое: #14

Баг космической темы
