### ISSUE TITLE
Загрузка бинарных файлов

### ISSUE THREAD

**Issue by SSS135** [MailRuChamps/raic-2020#25]
В планах есть использование Python + Rust (или C++). Это нужно для того, чтобы основную часть писать на Rust, а в питоне запускать нейросети. Но сейчас нельзя загружать .pyd файлы. Можно ли снять это ограничение?

**Comment by butorov** [comment]
На мой взгляд, бинарные файлы могли бы пригодиться всем, кто хочет нейронки тащить в соревнование. То есть я предложил бы не ограничиваться разрешением только .pyd-файлов, а разрешил бы все, если это не создаёт существенных проблем для поддержки запускающей/тестирующей системы.

**Comment by AKonia** [comment]
Берёшь плюсы или раст, берёшь base64 ну а дальше сам

**Comment by SSS135** [comment]
> Берёшь плюсы или раст, берёшь base64 ну а дальше сам

Если на сервере можно писать файлы. Надо будет проверить.

**Comment by AKonia** [comment]
> > Берёшь плюсы или раст, берёшь base64 ну а дальше сам
> 
> Если на сервере можно писать файлы. Надо будет проверить.

неужели из памяти прочитать нельзя ?

**Comment by SSS135** [comment]
Эмм, .pyd это по сути .dll файл. Разве его можно сразу в память загрузить?
Просто загрузить и использовать веса нейросети на сервер проблем нет, тут другое.

**Comment by AKonia** [comment]
вгрузить можно почти что угодно в mmap и подцепить, другой вопрос как к такому отнесутся организаторы, но вопрос это прямо dll ? Разве тестирующая система на винде ? А по поводу подгрузки СО говорит [вот что](https://stackoverflow.com/questions/8601950/load-pyd-files-from-a-zip-from-embedded-python)

**Comment by butorov** [comment]
> Берёшь плюсы или раст, берёшь base64 ну а дальше сам

Здесь, конечно, не вопрос о том, какой язык брать. В любом языке можно использовать бинарные данные,  сохранённые в base64-строке, или закодированные в строку любым из примерно [миллиона](https://en.wikipedia.org/wiki/Binary-to-text_encoding#Encoding_standards) способов.
Вопрос лишь в удобстве, и бессмысленном раздувании размера посылки, при кодировании этих данных в текст.

Конечно, встаёт вопрос: а не использует ли кто-то чужой код, скомпилированный в бинарный исполняемый файл, что будет на порядки сложнее обнаружить, нежели при only-text посылках. Но тут уже решать организаторам, спекулировать бесполезно, по-моему.

**Comment by AKonia** [comment]
@butorov Я уверен организаторы будут твёрдо против, т.к. ладно веса сетки возить так, но таскать исполнимые файлы и библиотеки - кто знает что туда запихнут пользователи, более того даже библиотеку сеток авторы по здравой логике должны завернуть, т.к. организаторы поддерживают языки в их исходном виде и если хочется сетки, то првильно всё же писать велосипед или искать готовый, разумного размера.

**Comment by kuviman** [comment]
Бинарные файлы загружать нельзя, только исходники
