### ISSUE TITLE
Вылет плеера под Linux при большом количестве объектов

### ISSUE THREAD

**Issue by Timofeyeff** [MailRuChamps/raic-2020#27]
При превышении количеством объектов на поле определенного порога плеер крашится с ошибкой:
ERROR - panicked at 'called `Option::unwrap()` on a `None` value', src/renderer/space/entity.rs:147:18
ERROR -    0: batbox::logger::init_with_level::{{closure}}                                                                   
   1: std::panicking::rust_panic_with_hook                                                                                   
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:490:17                               
   2: rust_begin_unwind                                                                                                      
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:388:5                                
   3: core::panicking::panic_fmt                                                                                             
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libcore/panicking.rs:101:14                              
   4: core::panicking::panic                                                                                                 
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libcore/panicking.rs:56:5                                
   5: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold                                       
   6: aicup2020::renderer::sprite::Renderer::draw                                                                            
   7: aicup2020::renderer::space::Renderer::draw                                                                             
   8: <aicup2020::renderer::Renderer as codegame::Renderer<aicup2020::model::Model>>::draw                                   
   9: <codegame::app::game_screen::GameScreen<G,R> as geng::state::State>::draw                                              
  10: <geng::debug_overlay::DebugOverlay as geng::state::State>::draw                                                        
  11: geng::context::run                                                                                                     
  12: aicup2020::run_with                                                                                                    
  13: aicup2020::run                                                                                                         
  14: std::rt::lang_start::{{closure}}                                                                                       
  15: std::rt::lang_start_internal::{{closure}}                                                                              
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/rt.rs:52:13                                       
      std::panicking::try::do_call                                                                                           
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:297:40                               
      std::panicking::try                                                                                                    
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:274:15                               
      std::panic::catch_unwind                                                                                               
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panic.rs:394:14                                   
      std::rt::lang_start_internal                                                                                           
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/rt.rs:51:25                                       
  16: main                                                                                                                   
  17: __libc_start_main                                                                                                      
  18: _start

**Comment by kuviman** [comment]
Скорее всего то же самое что и #14. Схематичный режим (кнопка V) должен работать

**Comment by Timofeyeff** [comment]
Да, вы правы, в схематичном режиме все работает. Спасибо.
