### ISSUE TITLE
Строительство юнитов должно останавливаться после успешного производства юнита.

### ISSUE THREAD

**Issue by brunneng** [MailRuChamps/raic-2020#28]
Очень не интуитивно, что после заказа юнита надо еще забоится о том, чтобы отменить приозводство. Должно быть так, захотел построить - построился один и все.

**Comment by kswaldemar** [comment]
Для всех сущностей повторяется последнее действие для id, если не перезаписано явно. Кому-то неудобно, кому-то наоборот. Можно зданию явно указать пустое действие, тогда производство остановится
