### ISSUE TITLE
Цвета в схематичном визуализаторе

### ISSUE THREAD

**Issue by dbf256** [MailRuChamps/raic-2020#30]
Спасибо за добавление цветов к тексту, единственное - не очень удачный жёлтый т.к. на нем плохо видны белые значки из-за того, что он очень яркий и при некоторых проблемах с цветовосприятием он смешивается с зеленым.
Нельзя ли сделать его каким-то более темным, например, оранжевым (#ff9c00)?

**Comment by kuviman** [comment]
Сделано
