### ISSUE TITLE
Запрос на добавление интерпретатора python pypy3.

### ISSUE THREAD

**Issue by kulievvitaly** [MailRuChamps/raic-2020#32]
Я использую python3 и провел тест производительности в сранении с pypy3. Запускал одну и ту же стратегию(код не изменялся) в локалранере. Запускал 3 раза, чтобы уменьшить рандом. Вот результаты:

pypy3      ram: 43mb cpu_time:  2.80sec  3.16sec  3.30sec
cpython3 ram:  8mb cpu_time: 27.09sec 37.35sec 36.39sec

Потребление памяти больше, но в пределах нормы. Зато быстродействие до 10х выше. Просьба к организаторам по возможности добавить pypy3 как отдельный язык.

**Comment by kulievvitaly** [comment]
Установить можно так:

sudo add-apt-repository ppa:pypy/ppa
sudo apt update
sudo apt install pypy3

**Comment by boriszaitsev** [comment]
Да, с питоном нужно что-то делать, у меня на сервере ни одна игра не доходит до 1000 тиков, вылетает по времени на от 500 до 700 тика. Никаких поисковых алогоритмов не использовал.
Если трудно добавлять пайпай, то хотя бы нумбу стоит попробовать добавить в питоний образ, можно будет хоть некоторые куски кода заджитить не сильно напрягаясь.
pip install numba
Если даже не взлетит почему-то, ничего не потеряем, использовать не обязатьельно ее.

**Comment by kulievvitaly** [comment]
Согласен. У меня тоже вылетает в заметном проценте случаев.

**Comment by kuviman** [comment]
Добавлено
