### ISSUE TITLE
debugUpdate игнорирует перемотку времени и присылает последний PlayerView

### ISSUE THREAD

**Issue by recar** [MailRuChamps/raic-2020#34]
void MyStrategy::debugUpdate(const PlayerView& playerView, DebugInterface& debug)
playerView - приходит всегда последний. По-идее должен приходить с текущего выбранного в локал раннере кадра

**Comment by oPOCCOMAXAo** [comment]
предыдущие кадры работают в режиме реплея, данные для debugUpdate уже были обработаны и весь вывод сохраняется

**Comment by kuviman** [comment]
Реализовано
