### ISSUE TITLE
Не запускать А* при перемещении в соседнюю клетку.

### ISSUE THREAD

**Issue by romka-u** [MailRuChamps/raic-2020#35]
Если в moveAction указана соседняя с юнитом клетка, не запускать А*, чтобы два юнита могли идти друг за другом (сейчас не могут ни при каком раскладе).

**Comment by lightkeeper217** [comment]
Согласно правилам сущности ходят в случайной последовательности. Если возможно, то необходимо изменить порядок последнего действия движения: если сущность согласно команде должна двинуться в соседнюю клетку (не после поиска пути, а сразу) и эта клетка занята дружественной сущностью, то выполнить сначала движение дружественной сущности. 
Таким образом для движения в колонне будет возможно на микроуровне.

**Comment by romka-u** [comment]
Кажется, дело всё же не в этом.

**Comment by kswaldemar** [comment]
Сейчас оно вообще не работает, если не запускать поиск, то будет работать если повезет с рандомом)

**Comment by kuviman** [comment]
> Сейчас оно вообще не работает, если не запускать поиск, то будет работать если повезет с рандомом)

Было бы не совсем так, ну да ладно. В новой версии можно идти вплотную
