### ISSUE TITLE
Kotlin ошибка при отправке стратегии

### ISSUE THREAD

**Issue by NamelessOne** [MailRuChamps/raic-2020#36]
При отправке стратегии текстом после обработки выдаёт ошибку:

`stdout:

stderr:
+ cd /output
+ java -Xmx250m -jar ./aicup2020-jar-with-dependencies.jar gameserver 31002 fa7fab65a417ca4d89634baf78e31c56bebd203d_1
Exception in thread "main" java.io.IOException: Unexpected EOF
	at util.StreamUtil.readBytes(StreamUtil.kt:23)
	at util.StreamUtil.readInt(StreamUtil.kt:35)
	at model.ServerMessage$Companion.readFrom(ServerMessage.kt:11)
	at Runner.run$aicup2020(Runner.kt:28)
	at Runner$Companion.main(Runner.kt:50)
	at Runner.main(Runner.kt)
Exit code:1
Memory used: 78MB
Consumed time: 12604`

При этом локально воспроизвести не получается - пробовал разные конфигурации, всё отрабатывает без падений.
Подскажите, в чём может быть причина? В какую сторону копать?

**Comment by kuviman** [comment]
Скорее всего в логе также есть `Player crashed: IO error: Invalid value`.

Это означает что вы передали некорректные значения и сервер закрыл соединение

**Comment by NamelessOne** [comment]
Больше ничего в логе нет.

А как можно определить, какие именно некорректные значения переданы и при каких условиях?
Весь дебаг убран.
Всё локально тестировалось кажется во всех возможных конфигурациях, падений не было.

**Comment by kuviman** [comment]
Какой номер посылки?

**Comment by NamelessOne** [comment]
После переисывания и оптимизации проблема ушла. 
Если больше никто с таким не сталкивался - видимо issue можно закрывать.
Номер послыки - 1111
