### ISSUE TITLE
Ruby 	Ошибка верификации

### ISSUE THREAD

**Issue by mrlewap** [MailRuChamps/raic-2020#38]
Отправляю пустую стратегию, выдает:

stdout:

stderr:
+ cd /output
+ ruby ./main.rb gameserver 31001 8d712b57ef8059d3ca6755b40ea785f90bd217a0_0
Exit code:137
Memory used: 13MB
Consumed time: 41032
TIME LIMIT EXCEEDED
Player crashed: IO error: Connection reset by peer (os error 104)

**Comment by kuviman** [comment]
В Ruby сейчас не используется буферизация общения с сервером, подозреваю это главная причина. `main.rb:SocketWrapper`.
Как включить буферизацию по докам не особо понятно, поможете?

**Comment by kuviman** [comment]
Видимо теперь норм?
