### ISSUE TITLE
Переделать melee солдат в разведчиков

### ISSUE THREAD

**Issue by recar** [MailRuChamps/raic-2020#40]
Поскольку сложно сбалансировать мечников и лучников, чтобы одни не вытеснили других, то я предлагаю сделать из мечников разведчиков.
Для этого 
1. Уменьшить лучникам область видимости до 4 клеток. То есть они могут стрелять дальше чем видят.
2. Убрать MELEE_UNIT и заменить на SCOUT_UNIT - область видимости 10, радиус атаки 3, жизнь 10, цена 10, атака 5

В первом раунде разведчики не нужны, но во втором у них появляется своя роль и в разведке и в бою, чтобы подсвечивать цели лучникам.

**Comment by kuviman** [comment]
Думаю этого делать уже не будем
