### ISSUE TITLE
Golang deployment

### ISSUE THREAD

**Issue by oPOCCOMAXAo** [MailRuChamps/raic-2020#5]
Cкрипт для компиляции и запуска стратегий на Golang работает некорректно.

Ошибка:
```
stdout:

stderr:
+ '[' compile '!=' base ']'
++ ls -1 /src/
++ wc -l
+ [[ 1 -eq 1 ]]
+ cp -f /src/my_strategy.go my_strategy.go
cp: cannot stat '/src/my_strategy.go': No such file or directory
```
Необходимо копировать целиком директорию `/src`, а не только файл `/src/my_strategy.go`.
Компилировать необходимо пакет `aicup2020`, который есть в стартер-паке.

**Comment by Pavel-Ryabov** [comment]
Такая же ошибка на Java, при отправке pom.xml и папки src

**Comment by kuviman** [comment]
При отправке архива необходимо сохранить ту же структуру, что и данный архив языкового пакета

**Comment by oPOCCOMAXAo** [comment]
@kuviman создал файл `/src/my_strategy.go`, но ошибка до сих пор есть и такая же:
```
stdout:

stderr:
+ '[' compile '!=' base ']'
++ ls -1 /src/
++ wc -l
+ [[ 1 -eq 1 ]]
+ cp -f /src/my_strategy.go my_strategy.go
cp: cannot stat '/src/my_strategy.go': No such file or directory
```
