### ISSUE TITLE
Предложение увеличить цены (Чтобы понизить концентрацию юнитов на карте)

### ISSUE THREAD

**Issue by AndrewB330** [MailRuChamps/raic-2020#53]
В данный момент после 300+ тика, вся карта усеяна юнитами. Было бы интересней смотреть за небольшими группками воюющих юнитов, а не "бутербродом" и хаосом :) **У юнитов просто не хватает мобильности, они создаются намного быстрее, чем могут добраться до противника.**

В большинстве игр подобного плана вводится штраф на добычу при большом количестве юнитов. Не думаю, что это лучшее решение, но можно рассмотреть и его. 

Нам бы могло подойти просто увеличить цены в 2-3 раза. При таком раскладе, время между построением юнитов в начале игры значительно возрастет, и у стратегий будет больше пространства для маневров. Так как на данный момент можно отстроить войско и рабов за 20-30 тиков (при наличии ресурсов), но за те же 20-30 тиков можно пройти всего 1/4 карты, и то с трудом.

P.S. и видимо нужно будет домножить ХП ресурсам на такой же коэффициент.

**Comment by ivlevAstef** [comment]
Можно решить две проблемы одним махом:
1. Бесполезность бараков. Что не говори, но во всех стратегия нормально является построить с десяток Бараков
2. Кучу юнитов.

Достаточно сделать чтобы юниты создавались не активными, а баракки умели их "чинить". Но только неактивных чинить.

Тогда каждый юнит будет строиться по долгу, и их не будет много.
Ресурсов станет больше - начнут строить баракки.

**Comment by recar** [comment]
Для начала я думаю было бы хорошо попробовать с исправленной ходьбой, чтобы можно было те же кучи юнитов сгруппировать в отряды.

**Comment by brunneng** [comment]
Не уверен, что этохо хорошая идея, хоть юнитов много - зато все развивается динамично и выглядит зрелищно. Иначе придется увеличивать число тиков в игре.

**Comment by AndrewB330** [comment]
> Не уверен, что этохо хорошая идея, хоть юнитов много - зато все развивается динамично и выглядит зрелищно. Иначе придется увеличивать число тиков в игре.

Не соглашусь, сейчас время игры ограничено размером карты. Когда боевые юниты доходят до чужих баз, игра заканчивается. Это занимает 200-300 тиков. Еще первые 200-300 тиков занимает развитие экономики. Увеличив стоимость мы замедляем как раз часть развития экономики давая возможность создавать рашевые стратегии (от которых кстати можно отбиваться турельками)

В данный момент игра и так длится 600-700 тиков в основном. И ресурсы часто уже заканчиваются после 600 тика

**Comment by AndrewB330** [comment]
> Можно решить две проблемы одним махом:
> 
> 1. Бесполезность бараков. Что не говори, но во всех стратегия нормально является построить с десяток Бараков
> 2. Кучу юнитов.
> 
> Достаточно сделать чтобы юниты создавались не активными, а баракки умели их "чинить". Но только неактивных чинить.
> 
> Тогда каждый юнит будет строиться по долгу, и их не будет много.
> Ресурсов станет больше - начнут строить баракки.

Это хорошее решение, НО: размеры бараков :)) Они занимаю слишком много места :) 
Я бы даже сказал, что идеальным улучшением было бы сделать стоимость всего х2 (размеры ресурсов х2), бараки размером 4*4 (чтобы помещались на карте) и ремонт юнитов (а не чтоб сразу спаунились активные)

Но это мое мнение :) Я просто предложил один из пунктов, потому что услышал в чате поддержку

**Comment by AndrewB330** [comment]
Для контекста, вот так сейчас выглядит 500 тик:
![image](https://user-images.githubusercontent.com/11033336/100930906-6c61a280-34f2-11eb-9a03-c0659754eac6.png)

Почти все мертвы, ресурсов (почти) нет, поле 80х80 с кучей юнитов :)
