### ISSUE TITLE
Добавить полупрозрачную подложку под информацию об игроках в схематичном локал ранере

### ISSUE THREAD

**Issue by recar** [MailRuChamps/raic-2020#57]
Сейчас либо не видно на черном, либо не видно на поле

![image](https://i.imgur.com/zy8dC52.png)

![image](https://user-images.githubusercontent.com/10685211/100912735-c77e9f80-34c8-11eb-8e90-28dd5c40b4f4.png)

**Comment by kuviman** [comment]
Добавлено

**Comment by boriszaitsev** [comment]
Это решило проблему со второй строчкой - зеленое на зеленом не было видно, теперь нормально.
Но самая первая строка - синего цвета, теперь не видна ни при каких движениях, темно-синий сливается с темной подложкой. Для людей со зрением ниже среднего это реальная проблема, а не дурацкий перфекционизм.
Может быть поменять цвет шрифта на более светлый (голубой), пусть он немного не совпадает с цветом игрока, все равно не перепутаешь.
Целый месяц же придется пялиться на эту строку, никуда от этого не убежать.
