### ISSUE TITLE
[Localrunner] debug graphics flickering

### ISSUE THREAD

**Issue by Karloid** [MailRuChamps/raic-2020#58]
Аналогичная проблема с прошлым годом, мб и в этом пофиксим? :)
https://github.com/MailRuChamps/raic-2019/issues/22

@kuviman 
> Исправлено (последний тик рисует дебаг данные с прошлого тика, если не стоять именно на последнем тике долгое время)

Мерцает дебаг вывод в локал ранее в режиме "live play" хочется что бы не мерцал и в режиме "live-play" было
видео 2020:

[debug_flickering.mov.zip](https://github.com/MailRuChamps/raic-2020/files/5632154/debug_flickering.mov.zip)

**Comment by kuviman** [comment]
Единственное изменение с прошлого года - новый тик рисуется сразу как только вы отправили какие то данные, иначе может быть предыдущий.

Это необходимо для корректной обработки debugUpdate.

Вероятно, можно добавить `DebugCommand::SetAutoFlush` и `DebugCommand::Flush` чтобы начинать отображать только после полной передачи всей графики

**Comment by kuviman** [comment]
Сделано
