### ISSUE TITLE
Разрешить идущим навстречу юнитам меняться местами

### ISSUE THREAD

**Issue by recar** [MailRuChamps/raic-2020#59]
Будет меньше пробок и заторов и более гладкое течение игры

**Comment by recar** [comment]
Это позволит избежать пробок в проходах между зданиями и лучникам, например, прятаться за мечников. Или рабочим убегать от врага и не мешать солдатам его атаковать.
За один ход все равно перемещение возможно максимум на одну клетку, то есть скорость юнитов не меняется.

Если один из юнитов стоит или движется не навстречу, то обмен не происходит.

**Comment by kuviman** [comment]
В общем, нет 🌚
