### ISSUE TITLE
[Local Runner] локальная симуляция не реплицируется

### ISSUE THREAD

**Issue by saw-ai** [MailRuChamps/raic-2020#60]
При выставлении seed в конфиге, одна и та же стратегия (против стартгая) дает разные результаты (в стратегии нет рандома)

**Comment by lookuut** [comment]
+

**Comment by tyamgin** [comment]
@kuviman Ping! Когда это исправишь?

**Comment by kulievvitaly** [comment]
Да, как раз сейчас очень актуально!

**Comment by kuviman** [comment]
Должно быть исправлено

**Comment by udalov** [comment]
Спасибо, но похоже не помогло. Например, если запустить четыре таких простейших стратегий на Котлине
```
fun getAction(pv: PlayerView, debug: DebugInterface?): Action {
    val result = mutableMapOf<Int, EntityAction>()
    for (e in pv.entities) {
        if (e.playerId != pv.myId) continue
        val enemy = pv.entities
            .filter { it.playerId != null && it.playerId != pv.myId }
            .minByOrNull { Math.abs(it.position.x - e.position.x) + Math.abs(it.position.y - e.position.y) }
        if (enemy != null) {
            result[e.id] = EntityAction().apply {
                attackAction = AttackAction(enemy.id, AutoAttack(666, emptyArray()))
                moveAction = MoveAction(enemy.position, true, true)
            }
        }
    }
    return Action(result)
}
```
несколько раз с сидом 123, то результаты получатся разные:
```
400 800 5600 600
600 600 600 600
600 600 600 600
600 600 800 400
500 700 800 400
5600 600 800 400
400 800 5600 600
600 600 600 600
```

Вроде в коде-обвязке рандома нет, и везде используются `mutableMapOf`, которые сохраняют порядок обхода (т.к. создаётся `LinkedHashMap`), поэтому похоже баг в раннере?

**Comment by kuviman** [comment]
@udalov в этом коде есть неоднозначность при выборе ближайшего соперника. `PlayerView::entities` не гарантирует порядок присланных entity.

Код может быть исправлен с помощью `pv.entities.sortedBy { it.id }`

**Comment by udalov** [comment]
Действительно, теперь воспроизводится. Спасибо! 👍

**Comment by kulievvitaly** [comment]
На питоне тоже воспроизводится на версии приложения 1.2.0.  Достаточно отсортировать список:
pypy: sorted(self.player_view.entities, key=lambda item: item.id)

**Comment by saw-ai** [comment]
@kuviman, Кажется, надо объявить о том, что нужно сортировать entities. Это не совсем очевидно

**Comment by tyamgin** [comment]
Я бы посортировал в следующем обновлении.

**Comment by kuviman** [comment]
В версии 1.2.1 добавлена сортировка
