### ISSUE TITLE
Добавить в PlayerView id уничтоженных Entities с прошлого тика

### ISSUE THREAD

**Issue by Jeen99** [MailRuChamps/raic-2020#68]
Сейчас на клиенте нужно хранить две коллекции сущностей (с прошлого тика и текущую), чтобы отслеживать уничтоженные.
Думаю, будет проще принимать эти данные от сервера, чтобы лишний раз не занимать память и процессорное время на клиенте (особенно касается скриптовых языков).

**Comment by recar** [comment]
Больше передаваемых данных - медленнее игры и локально и на сервере. Это не сложно посчитать  если отсортировать списки по айди.

**Comment by kuviman** [comment]
думаю это совсем незначительная часть использованного стратегиями времени, в протокол добавлять не вижу необходимости
