### ISSUE TITLE
Добавить награду выжившим игрокам в конце игры

### ISSUE THREAD

**Issue by oPOCCOMAXAo** [MailRuChamps/raic-2020#70]
Сейчас возникают ситуации, когда последний выживший игрок набрал меньше очков, чем один из уничтоженных и, соответственно, система защитает ему не победу.

Предлагаю добавить выжившим игрокам очки:
1. destroy_score за каждую выжившую союзную сущность, как за сохранение
2. 1 за каждую единицу ресурсов, т.к. эти ресурсы могли быть потрачены на постройки, а награда за постройки равняется их стоимости

Как пример игра: https://russianaicup.ru/game/view/22575
В ней игрок на 1 месте набрал на 900 очков больше выжившего, игра завершилась на 938 тике, соответственно, игрок на 2 месте мог за несколько тиков набрать эти 900 очков и занять первое место.

**Comment by akostyagin** [comment]
Я бы вообще радикально предложил: первому выбывшему сбрасывать очки до 1, второму - до 2, третьему - до 3.

**Comment by luckman** [comment]
В финале нужно сделать обязательно.
А вот в FFA спорно, нужно поддерживать, чтобы победитель был человек, нанёсший больший урон, а не сидящий постоянно на своей базе.

**Comment by oPOCCOMAXAo** [comment]
> В финале нужно сделать обязательно.
> А вот в FFA спорно, нужно поддерживать, чтобы победитель был человек, нанёсший больший урон, а не сидящий постоянно на своей базе.

Сидящий на базе очки обычно и не получает + растущая стоимость ему в финальном результате не поможет. Воюющие обычно спавнят много дополнительных юнитов дешевле и разменивают их, так что по очкам они будут лидировать

**Comment by boriszaitsev** [comment]
Нет смысла никакого в этих бонусах. 
Сделать слишком мало - все равно останутся игры где последний набрал меньше очков, слишком много - все превратится в скучную игру на выживание. 
Смысл текущей системы скора - сделать игру зрелищной, много боев. Бонус за выживание, чем больше его делать, тем сильнее будет обесценивать зарубы, сиди и копи ресурс.
В боях 1 на 1 это не важно совсем, и так будет выигрывать тот, кто больше наколотил.

**Comment by kuviman** [comment]
В финале выживший теперь всегда остается победителем, при 4 игроках остается по очкам
