### ISSUE TITLE
Добавить флаг "считать юнитов проходимыми"

### ISSUE THREAD

**Issue by iam1neo** [MailRuChamps/raic-2020#71]
в последней версии добавилась возможность юнитам занимать места, которые только что освободились.
вот только текущий автопоиск пути с А* никогда не воспользуется этой возможностью.
Наоборот, пока свои юниты считаются непроходимыми - идущие сзади в узком проходе развернутся и пойдут в обход.
Однако, в первой версии, когда флаг breakThrough приводил к убийству своих же юнитов - вышеописанной проблемы не было. юниты шли максимально друг за другом.
Предлагаю добавить еще один флаг в MoveAction и предоставить выбор, в зависимости от потребностей считать своих проходимыми или нет

**Comment by iam1neo** [comment]
как вариант - вернуть назад часть логики breakThrough, которая изначально считала своих проходимыми. но не возвращать ту ее кровожадную часть, которая начинала их убивать. то есть при breakThrough=true проходимы все вражеские сущности + свои умеющие двигаться. но атаковать только вражеские сущности
но все же более гибко было бы иметь 2 отдельных флага для своих и для чужих

**Comment by kuviman** [comment]
Встроенный алгоритм поиска пути предназначен для быстрого старта, для лучшего поиска пути стоит писать свои реализации
