### ISSUE TITLE
Более строгий порядок обработки действий.

### ISSUE THREAD

**Issue by ud1** [MailRuChamps/raic-2020#8]
Насколько понял из обсуждения, сейчас для каждого юнита обрабатываются все его действия включая движение, перед тем как начать обрабатывать действия другого юнита. Но это добавляет сильный эффект случайности в сражениях, мешает микроконтролю юнитов.
Например юнит входит всего на один тик в зону поражения турели, в следующем тике выходит из зоны. Логично, что если он был в зоне поражения только 1 тик, то ему турель может нанести урона ровно на один тик. Но если порядок действий не определен, на деле может оказать 0/1/2 тика урона. Например сначала может посчитаться движение юнита - он входит в зону поражения турели, потом просчитается турель и нанесет ему урон. А в следующем тике наоборот, сначала если просчитается турель, она нанесет ему еще один тик урона, и только потом движение юнита выходящего из зоны поражения.

Предлагаю поменять порядок расчет на следующий.
1. Случайным образом пересортируем все юниты и здания.
2. Для каждого юнита/здания просчитываем действия атаки/постройки/ремонта. При этих вычислениях не учитываем для здоровья границы 0-maxhealth.
3. Для каждого юнита приводим здоровья к диапазону 0-maxhealth, у тех у кого здоровье оказывается равным 0, удаляем из мира. Ограничение по maxhealth применяем в этом отдельном шаге, а не на шаге 2, потому что юниту может наноситься урон и ремонт в разном порядке, и надо сначала посчитать суммарное значение здоровья после всех воздействий на него.
4. В несколько итераций применяем движение оставшихся юнитов, расчеты делаем в том случайном порядке, что получился в пункте 1. Несколько итераций нужны, чтобы юниты могли двигаться строем, вплотную друг другу. В каждой итерации пытаемся сдвинуть юниты, которые не смогли сдвинуться до этого, из-за того, что место которое они хотят занять было занято, и проводим итерации пока получается сдвинуть хоть кого-то.

**Comment by ud1** [comment]
Еще не очень понятно, почему нельзя двигаться во время стрельбы? Фактически надо хранить у юнита флаг, что он выполнил одно из предыдущих действий - атаки/постройки/ремонта, и если выполнил, то он уже не может в этом тике двигаться.
Мне кажется такое ограничение можно убрать, игры будут более динамичными, но тут не настаиваю на изменении правил, это все таки скорее относится к общему дизайну правил игры, а не к деталям реализации.

**Comment by ud1** [comment]
Еще интересный момент, а как сейчас начисляются очки за убийство? Если встретятся 3 юнита, все 3 от разных игроков, и два юнита в один тик наносят урон третьему и убивают его, кому из двух игроков начислятся очки? Можно сослаться на рандом, но мне кажется более честно будет их разделить между обоими игроками, вычислисть кто сколько в этот тик нанес урона, и разделить награду пропорционально этому числу.

**Comment by mortido** [comment]
Было мнение от организаторов, что то, что правит 4 пункт, на самом деле желаемое поведение. Не уверен, что полностью разделаю их мнение в этом, но как альтернативное решение для более прогнозируемого поведения можно попробовать следующее:
1 - шафлим сущности как раньше
2 - для каждого действия [атака, постройка, ремонт, перемещение] пройтись по сущностям и выполнить их, если они необходимы и возможны. Порядок действий можно поменять (например, если хочется, чтобы приоритетным было движение, а потом защищающий юнит мог в этот же ход подстрелить наступающего)
3 - также как раньше удаляем сущности со здоровьем <= 0

По факту сюда все еще можно добавить "итеративное" перемещение (это больше про запинание об своих), но уже это решает проблему с башней и юнитом, про которую ты писал выше.

Кажется в этом ишью уже собралось три запроса на изменения: итеративная ходьба, разделение действий, возможность ходить и стрелять.

**Comment by DragoonXen** [comment]
Возможность ходить и стрелять, кмк, совсем отдельный вопрос

**Comment by ud1** [comment]
Менять порядок мне кажется не стоит, лучше расчеты атаку/постройку/ремонт делать в старых координатах, и только потом двигать.
И итеративная ходьба и разделение действий считаю очень необходимыми вещами.

А вот ходить и стрелять это уже спорный вопрос. Даже в голову сейчас пришло, разрешить это делать только милишникам, это даст им больше мобильности, и лучники не смогут просто так от них убежать, надо будет когда милишник приблизился в плотную к цели давать ему приказ двигать ровно на нее, и все, у лучника нет шансов убежать.

**Comment by mortido** [comment]
Ну, кстати, да. Разделять атаку, ремонт и постройку нет смысла друг от друга. Если это делается до движения, то все должно быть хорошо. Тогда дико плюсую это изменение. Насчет итеративной ходьбы не так принципиален)

**Comment by boriszaitsev** [comment]
Пддерживаю предложение обрабатывать сначала действия, потом расчет здоровья, потом перемещения.
Насчет четвертого пункта: итеративное разрешение коллизий будет работать, но в некоторых вырожденных случаях это может привести к довольно большому количеству итераций и сильно замедлит работу рефери. Например передвижение колонной/змейкой может потребовать столько итераций, сколько юнитов в колонне, если порядок проверки случайный. То есть сложность вместо линейной становится квадратичной.
Я предлагаю обсчитывать действия каждого игрока в том порядке, в котором он отдал свои команды. Но брать действие для следующего обсчета выбирая случайно именно игрока, из чьей очереди брать команду мува. Тогда коллизий между юнитами одного игрока не будет, если он конечно сам об этом позаботится, можно будет ходить строем. Возможно останутся коллизии между юнитами разных игроков, но это и случается довольно редко, и вполне вписывается в концепцию случайных привратностей войны. Сложность обсчета не увеличится - останется линейной.

**Comment by ud1** [comment]
Даже если итераций будет много, мне кажется можно это сделать достаточно быстро. Не думаю, что этот просчет будет дороже, чем тот же самый A*, который и так может запускаться всех юнитов.

**Comment by DragoonXen** [comment]
Уверен баг этой игры проистекает всё ещё от нашей обработки действий

https://russianaicup.ru/game/view/2842

**Comment by iam1neo** [comment]
Согласен с устранением эффекта случайности, но если применить предложение "обрабатывать сначала действия, потом расчет здоровья, потом перемещения", по-моему, это приведет в одному отрицательному последствию: у обороняющихся не будет преимущества.
Если у меня стоят в обороне защитники, с единственной командой - убивать подходящих, то они как бы в укреплении и на готове, нападающие при подходе в радиус обстрела должны получить безответный первый удар, потому что они делают move, а мои attack. и лишь потом обмениваются взаимными ударами, если переживут первый.
Так что стоит в предложенном варианте сделать еще один просчет move между (1) и (2), а (4) оставить для перемещений поверх умерших, кто до этого не смог никак сходить

**Comment by ud1** [comment]
Т.е. ты предлагаешь обороняющимся начать стрелять в тот момент, когда враг находится вне зоны досягаемости, ожидая, что он войдет в нее, и сразу получит урон? А если не станет входить? Или что если войти в зону могут сразу двое, ты сделал ставку на одного их них, а на самом деле он не стал приближаться, а приблизился другой?
Или что если враг в зоне поражения, ты делаешь выстрел ожидая что гарантированно попадешь, а он вышел из зоны?

В общем думаю так не работает, все расчеты надо вести в текущих координатах и потом уже делать движения.

**Comment by ud1** [comment]
> Уверен баг этой игры проистекает всё ещё от нашей обработки действий
> 
> https://russianaicup.ru/game/view/2842

Думаю это не баг, видимо просто строители решили починить вражеские здания. А кто сказал, что чинить можно только свои?

**Comment by iam1neo** [comment]
> 
> 
> Т.е. ты предлагаешь обороняющимся начать стрелять в тот момент, когда враг находится вне зоны досягаемости, ожидая, что он войдет в нее, и сразу получит урон? А если не станет входить? Или что если войти в зону могут сразу двое, ты сделал ставку на одного их них, а на самом деле он не стал приближаться, а приблизился другой?
> Или что если враг в зоне поражения, ты делаешь выстрел ожидая что гарантированно попадешь, а он вышел из зоны?
> 
> В общем думаю так не работает, все расчеты надо вести в текущих координатах и потом уже делать движения.

войдет или не войдет, угадал я с выбором мишени или нет - это уже вопрос стратегии, а не игровой механики.
я про саму суть "бонуса укрепления в обороне". если я не двигаюсь и "стреляю на упреждение", да, на расстояние 6, и так вышло, что чужой юнит действительно пошел в нападение на меня, и я угадал с мишенью - бонус мне обороняющемуся за подготовленность, атака проходит успешно, нападающий получает безответный первый удар.
собственно оно и сейчас так работает, но из-за рандома, в половине случаев

**Comment by boriszaitsev** [comment]
У обороняющегося и так есть существенный перевес - пока враг ползет до базы через узкие проходы, спотыкаясь друг об друга,  можно успеть наплодить кучу юнитов и туррелей и расставить их как удобно для обороны.
Ну вообще как-то не в ту сторону зашли, тема то не про правку баланса, а про то, чтобы внести хоть какую-то определенность в порядок расчета боев. С полным рандомом получаются какие-то квантовые бои, может юнит всех вынесет, а может умрет ни разу ни выстрелив.

**Comment by DragoonXen** [comment]
> > Уверен баг этой игры проистекает всё ещё от нашей обработки действий
> > https://russianaicup.ru/game/view/2842
> 
> Думаю это не баг, видимо просто строители решили починить вражеские здания. А кто сказал, что чинить можно только свои?

Взгляни на начисление очков человеку :)

**Comment by kuviman** [comment]
Итак, в этом ишью много всего написано, но: одна из частей теперь реализована - сначала все атаки, потом все постройки и тп. При поиске пути используется состояние на начало тика

**Comment by kuviman** [comment]
Новая версия. Пока есть куда двигать двигаем, при коллизиях рандом. Кажется можно закрывать
