### ISSUE TITLE
Добавить в локалранер статистику по количеству юнитов каждого типа.

### ISSUE THREAD

**Issue by boriszaitsev** [MailRuChamps/raic-2020#80]
Это ключевая статистика, была бы полезна большинству игроков для отладки.
Особенно после введения динамической стоимости юнитов.
Сейчас написано: population: 21/25.

Предлагаю допавить после этого еще три значения - количество юнитов каждого типа:
чтобы стало так: population: 21/25 (10 6 5). 
Это будет обозначать что 21 юнит это 10 рабочих, 6 мечников и 5 лучников. В том же порядке, что и в перечислении model.EntityType.

**Comment by deniskolsanov** [comment]
Нужно бооольше графиков!
Я считаю нужно на каждого игрока оформить график его энтити и денег

**Comment by kuviman** [comment]
Добавили
