### ISSUE TITLE
Увеличить радиус поражения турели

### ISSUE THREAD

**Issue by yufituris** [MailRuChamps/raic-2020#82]
Турели стали дешевле (хотя де-факто не так сильно, если учитывать затраты ходов рабочих на постройку), однако теперь из-за возможности лечения юнитов лучники потенциально могут разрушать турели вообще без потерь. Как ни крутись есть как минимум две клетки, откуда её могут атаковать лучники, а отвечать им может она одна. Лучники могут туда заходить, наносить урон и уходить лечиться. 
Для баланса можно было бы увеличить радиус поражения турелей. Заодно появится смысл строить перед ними стены и лучники не смогут безнаказанно их расстреливать.

**Comment by Arukim** [comment]
Было мнение в чате что после такого изменения туррели могут стать опасным средством харрасмента рабочих. Но это может быть как плюсом так и минусом.

**Comment by yufituris** [comment]
А в чем минус? Ну это по крайней мере разнообразит игру.  А вот наличие бесполезных сущностей явно нет. Сейчас лучники могут быть опасным средством харрасмента рабочих, и что?

**Comment by Arukim** [comment]
Я за изменение, просто баланс очень тонкая штука. Хотел подсветить этот момент.

**Comment by brunneng** [comment]
Мне кажется потенциал турелей в их текущем виде пока недооценен. Надо немного подождать и посмотреть на стратегии, которые будут их использовать.

**Comment by yufituris** [comment]
> Мне кажется потенциал турелей в их текущем виде пока недооценен. Надо немного подождать и посмотреть на стратегии, которые будут их использовать.

Тут дело не только в туреле, но и в стене, которая де-факто подорожала в 6 раз.

**Comment by kuviman** [comment]
Меняться баланс уже не будет (скорее всего)
