### ISSUE TITLE
Поменять цветовую схему в информацию об игроках в локалранере

### ISSUE THREAD

**Issue by boriszaitsev** [MailRuChamps/raic-2020#83]
![image](https://user-images.githubusercontent.com/7762001/101204473-1590d000-368e-11eb-880d-5623a01f3c39.png)

Была добавлена темная подложка по этому issue:
https://github.com/MailRuChamps/raic-2020/issues/57

Темная положка решила проблему со второй строчкой - зеленое на зеленом не было видно, теперь нормально.
Но самая первая строка - синего цвета, теперь не видна ни при каких движениях поля, темно-синий всегда сливается с темной подложкой. Для людей со зрением ниже среднего это реальная проблема, а не дурацкий перфекционизм.
Может быть поменять цвет шрифта на более светлый (голубой), пусть он немного не совпадает с цветом игрока, все равно не перепутаешь. 
Речь идет именно о цвете строки с информацией вверху, сами юниты и строения синего цвета отлично смотрятся на поле светлого цвета.
Целый месяц же придется пялиться на эту строку, никуда от этого не убежать, а тут даже шрифт не увеличить никак.

**Comment by recar** [comment]
Возможно сам синий цвет игрока стоит заменить - в 3д синие юниты не видно на черном фоне

**Comment by iam1neo** [comment]
может также передвинуть эту панель к левой границе? карта квадратная, мониторы 16:9, слева-справа место зря пропадает
