### ISSUE TITLE
golang: юниты упорно не желают создаваться. Баг?

### ISSUE THREAD

**Issue by prospero78** [MailRuChamps/raic-2020#84]
Ниже примерный код, вызывается каждый тик. Результат отсутствует
```golang
if player.Player.Resource() > 20 && len(poolbuilder.PoolBuilder.Builders()) <= 10 {
		log.Printf("TBaseBuilder.GetAct(): build unit.builder base=%v:%v unit=%v:%v\n",
			sf.base.Position.X, sf.base.Position.Y, x,y)
		act = &model.EntityAction{
			BuildAction: &model.BuildAction{
				EntityType: model.EntityTypeBuilderUnit,
				Position: model.Vec2Int32{
					X: x,
					Y: y,
				},
			},
		}
		return act
	}
return nil
```
В условие точно цикл заходит, точно возвращает не `nil`. Но реакции `localRunner` ноль.

Перебрал три десятка вариантов для позиции создания юнита от жёсткого смещения до откровенного беспардонного рандома. Ничего не выходит. С клавиатуры получается управлять, создавать юнита за противника.

**Comment by Arukim** [comment]
А какие все же x,y используются? Я бы предложил попробовать изменить код так, чтобы приказ отдавался относительно базы.


Position: model.Vec2Int32{
   X: sf.base.Position.X,
   Y: sf.base.Position.Y-1,
}

**Comment by prospero78** [comment]
На самом деле именно так и делал (один из опробованных вариантов).

**Comment by kuviman** [comment]
Для создания юнитов есть много требований - место, расстояние (1), ресурсы, еда
