### ISSUE TITLE
[localrunner] [bug] в режиме fancy визуализации не применяется раскраска к юнитам и зданиям

### ISSUE THREAD

**Issue by Karloid** [MailRuChamps/raic-2020#9]
chrome mac os

![image](https://user-images.githubusercontent.com/2398460/100542220-d01d6e80-3259-11eb-892a-14de77a8a2ab.png)
![image](https://user-images.githubusercontent.com/2398460/100542248-e3c8d500-3259-11eb-8ee9-8f7d63d2db95.png)

все здания и юниты раскрашены в синий

PS:
в целом в режиме fancy непонятно что происходит т.к. синие юниты на синем фоне

а вот в режиме схематической визуализации не помешали бы HP бары

**Comment by kuviman** [comment]
Fixed
